import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:analyzer/source/line_info.dart';

/// Whether [unit] has a language version that allows dot shorthands.
bool supportsDotShorthands(CompilationUnit unit) =>
    unit.featureSet.isEnabled(.dot_shorthands);

const generatedHeaderMarker = 'GENERATED CODE - DO NOT MODIFY BY HAND';

const flutterFireHeaderMarker = 'FILE GENERATED BY FLUTTERFIRE CLI';

/// Whether the first lines of [content] carry a generated-code header.
bool isGeneratedSource(String content) {
  const markers = [generatedHeaderMarker, flutterFireHeaderMarker];
  var start = 0;
  for (var line = 0; line < 10 && start <= content.length; line++) {
    final br = content.indexOf('\n', start);
    final end = br == -1 ? content.length : br;
    final upper = content.substring(start, end).toUpperCase();
    if (markers.any(upper.contains)) {
      return true;
    }
    if (br == -1) break;
    start = br + 1;
  }
  return false;
}

/// One place where a type-qualified member can drop its type name.
class Finding {
  Finding({
    required this.path,
    required this.line,
    required this.column,
    required this.offset,
    required this.end,
    required this.source,
    required this.shorthand,
    required this.contextType,
    required this.deleteStart,
    required this.deleteEnd,
  });

  final String path;
  final int line;
  final int column;
  final int offset;
  final int end;

  /// The expression as written, for example `Color.red`.
  final String source;

  /// The expression in shorthand form, for example `.red`.
  final String shorthand;

  final String contextType;

  /// Start of the range to delete, the type name.
  final int deleteStart;

  /// End of the range to delete, just before the dot.
  final int deleteEnd;
}

/// Walks a resolved unit and collects every [Finding].
///
/// Generated sources and units below language version 3.10 yield nothing.
class ShorthandVisitor extends RecursiveAstVisitor<void> {
  ShorthandVisitor(ResolvedUnitResult result)
    : this.forUnit(
        unit: result.unit,
        content: result.content,
        path: result.path,
      );

  ShorthandVisitor.forUnit({
    required CompilationUnit unit,
    required this.content,
    required this.path,
  }) : lineInfo = unit.lineInfo;

  final String content;
  final String path;
  final LineInfo lineInfo;
  final findings = <Finding>[];

  @override
  void visitCompilationUnit(CompilationUnit node) {
    if (!supportsDotShorthands(node)) return;
    if (isGeneratedSource(content)) return;
    super.visitCompilationUnit(node);
  }

  @override
  void visitInstanceCreationExpression(InstanceCreationExpression node) {
    super.visitInstanceCreationExpression(node);
    final name = node.constructorName.name;
    final period = node.constructorName.period;
    final namedType = node.constructorName.type;
    if (name == null || period == null) return;
    if (namedType.typeArguments != null) return;
    final constructor = node.constructorName.element;
    if (constructor == null) return;
    _consider(
      node: node,
      declaringType: namedType.element,
      member: constructor,
      memberName: name.name,
      deleteStart: namedType.offset,
      deleteEnd: period.offset,
    );
  }

  @override
  void visitMethodInvocation(MethodInvocation node) {
    super.visitMethodInvocation(node);
    final target = node.target;
    final operator = node.operator;
    if (target is! Identifier || operator == null || operator.lexeme != '.') {
      return;
    }
    final declaringType = _typeElementOf(target);
    if (declaringType == null) return;
    final member = node.methodName.element;
    if (member is! MethodElement || !member.isStatic) return;
    _consider(
      node: node,
      declaringType: declaringType,
      member: member,
      memberName: node.methodName.name,
      deleteStart: target.offset,
      deleteEnd: operator.offset,
    );
  }

  @override
  void visitPropertyAccess(PropertyAccess node) {
    super.visitPropertyAccess(node);
    final target = node.target;
    if (target is! Identifier || node.operator.lexeme != '.') return;
    final declaringType = _typeElementOf(target);
    if (declaringType == null) return;
    _considerStaticValue(
      node: node,
      declaringType: declaringType,
      member: node.propertyName.element,
      memberName: node.propertyName.name,
      deleteStart: target.offset,
      deleteEnd: node.operator.offset,
    );
  }

  @override
  void visitPrefixedIdentifier(PrefixedIdentifier node) {
    super.visitPrefixedIdentifier(node);
    final declaringType = _typeElementOf(node.prefix);
    if (declaringType == null) return;
    _considerStaticValue(
      node: node,
      declaringType: declaringType,
      member: node.identifier.element,
      memberName: node.identifier.name,
      deleteStart: node.offset,
      deleteEnd: node.period.offset,
    );
  }

  void _considerStaticValue({
    required Expression node,
    required InterfaceElement declaringType,
    required Element? member,
    required String memberName,
    required int deleteStart,
    required int deleteEnd,
  }) {
    if (memberName == 'values' && declaringType is EnumElement) return;
    final resolved = switch (member) {
      GetterElement(isStatic: true) => member,
      FieldElement(isStatic: true) => member,
      _ => null,
    };
    if (resolved == null) return;
    _consider(
      node: node,
      declaringType: declaringType,
      member: resolved,
      memberName: memberName,
      deleteStart: deleteStart,
      deleteEnd: deleteEnd,
    );
  }

  void _consider({
    required Expression node,
    required Element? declaringType,
    required Element member,
    required String memberName,
    required int deleteStart,
    required int deleteEnd,
  }) {
    if (declaringType is! InterfaceElement) return;
    final context = _contextType(node);
    if (context == null) return;
    final contextElement = context.element;
    if (contextElement is! InterfaceElement) return;
    if (contextElement != declaringType &&
        !_supertypeMemberRedirects(node, context, memberName, member)) {
      return;
    }
    final location = lineInfo.getLocation(node.offset);
    findings.add(
      Finding(
        path: path,
        line: location.lineNumber,
        column: location.columnNumber,
        offset: node.offset,
        end: node.end,
        source: content.substring(node.offset, node.end).split('\n').first,
        shorthand: content.substring(deleteEnd, node.end).split('\n').first,
        contextType: context.getDisplayString(),
        deleteStart: deleteStart,
        deleteEnd: deleteEnd,
      ),
    );
  }

  bool _supertypeMemberRedirects(
    Expression node,
    DartType context,
    String memberName,
    Element member,
  ) {
    final contextElement = context.element! as InterfaceElement;
    if (member is GetterElement) member = member.variable;
    if (member is FieldElement) {
      return _supertypeConstAliases(node, context, memberName, member);
    }
    if (member is! ConstructorElement) return false;
    var candidate = contextElement.constructors
        .where((c) => (c.name ?? 'new') == memberName)
        .firstOrNull;
    final seen = <ConstructorElement>{};
    while (candidate != null && seen.add(candidate)) {
      if (candidate == member) return true;
      candidate = candidate.redirectedConstructor?.baseElement;
    }
    return false;
  }

  /// Whether the context type declares a static const of the same name that
  /// evaluates to the same object as [member], the way
  /// `EdgeInsetsGeometry.zero` aliases `EdgeInsets.zero`.
  ///
  /// The alias's own initializer stays as written: rewriting it would make the
  /// constant refer to itself. The alias's declared type must fit the context,
  /// or the shorthand would not type-check where the written form did.
  bool _supertypeConstAliases(
    Expression node,
    DartType context,
    String memberName,
    FieldElement member,
  ) {
    if (!member.isConst) return false;
    final contextElement = context.element! as InterfaceElement;
    final alias = contextElement.getField(memberName);
    if (alias == null || !alias.isStatic || !alias.isConst) return false;
    final declaration = node.thisOrAncestorOfType<VariableDeclaration>();
    if (declaration?.declaredFragment?.element == alias) return false;
    final typeSystem = alias.library.typeSystem;
    if (!typeSystem.isSubtypeOf(alias.type, context)) return false;
    final written = member.computeConstantValue();
    final viaContext = alias.computeConstantValue();
    return written != null && written == viaContext;
  }

  DartType? _contextType(Expression expression) {
    var node = expression;
    var parent = node.parent;
    while (parent is ParenthesizedExpression) {
      node = parent;
      parent = node.parent;
    }

    if (parent is ArgumentList) {
      return _argumentContext(parent, node.correspondingParameter);
    }

    switch (parent) {
      case NamedArgument(parent: final ArgumentList list):
        return _argumentContext(list, parent.correspondingParameter);
      case ConditionalExpression(:final thenExpression, :final elseExpression)
          when node == thenExpression || node == elseExpression:
        return _contextType(parent);
      case VariableDeclaration(:final initializer)
          when node == initializer && parent.parent is VariableDeclarationList:
        return (parent.parent! as VariableDeclarationList).type?.type;
      case AssignmentExpression(:final rightHandSide, :final operator)
          when node == rightHandSide && operator.lexeme == '=':
        return parent.writeType;
      case BinaryExpression(:final rightOperand, :final operator)
          when node == rightOperand &&
              (operator.lexeme == '==' || operator.lexeme == '!='):
        return _nonNull(parent.leftOperand.staticType);
      case FormalParameterDefaultClause(:final value) when node == value:
        final owner = parent.parent;
        return owner is FormalParameter
            ? _nonNull(owner.declaredFragment?.element.type)
            : null;
      case ConstructorFieldInitializer(:final expression)
          when node == expression:
        return parent.fieldName.element is FieldElement
            ? (parent.fieldName.element! as FieldElement).type
            : null;
      case ConstantPattern():
        return _nonNull(parent.matchedValueType);
      case ReturnStatement():
        return _returnContext(parent);
      case ExpressionFunctionBody():
        return _returnContext(parent);
      case ListLiteral() || SetOrMapLiteral():
        return _collectionElementContext(parent as TypedLiteral, node);
      case _:
        return null;
    }
  }

  DartType? _collectionElementContext(TypedLiteral literal, Expression node) {
    final arguments = literal.typeArguments?.arguments;
    if (arguments != null) {
      if (literal is ListLiteral ||
          literal is SetOrMapLiteral && arguments.length == 1) {
        return arguments.first.type;
      }
      return null;
    }
    final outer = _contextType(literal);
    if (outer is! InterfaceType) return null;
    final element = outer.element;
    if (element.name != 'List' &&
        element.name != 'Set' &&
        element.name != 'Iterable') {
      return null;
    }
    return outer.typeArguments.length == 1 ? outer.typeArguments.first : null;
  }

  DartType? _argumentContext(
    ArgumentList list,
    FormalParameterElement? parameter,
  ) {
    if (parameter == null) return null;
    final inferred = _inferredTypeParameters(list);
    if (inferred == null) return null;
    if (_mentionsAny(parameter.baseElement.type, inferred)) return null;
    return _nonNull(parameter.type);
  }

  Set<TypeParameterElement>? _inferredTypeParameters(ArgumentList list) {
    final result = <TypeParameterElement>{};
    switch (list.parent) {
      case MethodInvocation(:final methodName, :final typeArguments):
        final element = methodName.element;
        if (element is! ExecutableElement) return null;
        if (typeArguments == null) {
          result.addAll(element.baseElement.typeParameters);
        }
      case FunctionExpressionInvocation(:final element, :final typeArguments):
        if (element == null) return null;
        if (typeArguments == null) {
          result.addAll(element.baseElement.typeParameters);
        }
      case InstanceCreationExpression(:final constructorName):
        final element = constructorName.element;
        if (element == null) return null;
        if (constructorName.type.typeArguments == null) {
          result.addAll(element.baseElement.typeParameters);
          result.addAll(element.enclosingElement.typeParameters);
        }
      case Annotation(:final element, :final typeArguments):
        if (element is! ConstructorElement) return null;
        if (typeArguments == null) {
          result.addAll(element.baseElement.typeParameters);
          result.addAll(element.enclosingElement.typeParameters);
        }
      case RedirectingConstructorInvocation() ||
          SuperConstructorInvocation() ||
          EnumConstantArguments():
        break;
      case _:
        return null;
    }
    return result;
  }

  bool _mentionsAny(DartType type, Set<TypeParameterElement> parameters) {
    if (parameters.isEmpty) return false;
    final names = parameters.map((p) => p.name).toSet();
    var found = false;
    void walk(DartType current) {
      if (found) return;
      if (current is TypeParameterType) {
        if (names.contains(current.element.name)) found = true;
        return;
      }
      if (current is InterfaceType) {
        current.typeArguments.forEach(walk);
      } else if (current is FunctionType) {
        walk(current.returnType);
        for (final parameter in current.formalParameters) {
          walk(parameter.type);
        }
      } else if (current is RecordType) {
        for (final field in current.positionalFields) {
          walk(field.type);
        }
        for (final field in current.namedFields) {
          walk(field.type);
        }
      }
    }

    walk(type);
    return found;
  }

  DartType? _returnContext(AstNode node) {
    final body = node.thisOrAncestorOfType<FunctionBody>();
    if (body == null || body.isGenerator) return null;
    final owner = body.parent;
    TypeAnnotation? declared;
    switch (owner) {
      case MethodDeclaration():
        declared = owner.returnType;
      case FunctionExpression(parent: FunctionDeclaration(:final returnType)):
        declared = returnType;
      case _:
        return null;
    }
    final type = declared?.type;
    if (type == null) return null;
    if (!body.isAsynchronous) return _nonNull(type);
    if (type is! InterfaceType) return null;
    final name = type.element.name;
    if ((name != 'Future' && name != 'FutureOr') ||
        type.typeArguments.length != 1) {
      return null;
    }
    return _nonNull(type.typeArguments.first);
  }

  DartType? _nonNull(DartType? type) {
    if (type == null) return null;
    if (type is DynamicType || type is InvalidType) return null;
    if (type is! InterfaceType) return null;
    return type;
  }

  InterfaceElement? _typeElementOf(Identifier identifier) {
    final element = switch (identifier) {
      PrefixedIdentifier() when identifier.prefix.element is PrefixElement =>
        identifier.identifier.element,
      SimpleIdentifier() => identifier.element,
      _ => null,
    };
    return element is InterfaceElement ? element : null;
  }
}
